In [36]:
import pandas as pd
import numpy as np
from pandas import DataFrame,Series
from __future__ import division

In [3]:
ages=pd.read_csv("all-ages.csv")
r_g=pd.read_csv("recent-grads.csv")

In [4]:
# This data gives us the employment data for all ages
ages.head()

,Major_code,Major,Major_category,Total,Employed,Employed_full_time_year_round,Unemployed,Unemployment_rate,Median,P25th,P75th
0,1100,GENERAL AGRICULTURE,Agriculture & Natural Resources,128148,90245,74078,2423,0.026147,50000,34000,80000
1,1101,AGRICULTURE PRODUCTION AND MANAGEMENT,Agriculture & Natural Resources,95326,76865,64240,2266,0.028636,54000,36000,80000
2,1102,AGRICULTURAL ECONOMICS,Agriculture & Natural Resources,33955,26321,22810,821,0.030248,63000,40000,98000
3,1103,ANIMAL SCIENCES,Agriculture & Natural Resources,103549,81177,64937,3619,0.042679,46000,30000,72000
4,1104,FOOD SCIENCE,Agriculture & Natural Resources,24280,17281,12722,894,0.049188,62000,38500,90000

In [5]:
#This data gives us the employment data for recent grads.
r_g.head()

,Rank,Major_code,Major,Major_category,Total,Sample_size,Men,Women,ShareWomen,Employed,...,Part_time,Full_time_year_round,Unemployed,Unemployment_rate,Median,P25th,P75th,College_jobs,Non_college_jobs,Low_wage_jobs
0,1,2419,PETROLEUM ENGINEERING,Engineering,2339,36,2057,282,0.120564,1976,...,270,1207,37,0.018381,110000,95000,125000,1534,364,193
1,2,2416,MINING AND MINERAL ENGINEERING,Engineering,756,7,679,77,0.101852,640,...,170,388,85,0.117241,75000,55000,90000,350,257,50
2,3,2415,METALLURGICAL ENGINEERING,Engineering,856,3,725,131,0.153037,648,...,133,340,16,0.024096,73000,50000,105000,456,176,0
3,4,2417,NAVAL ARCHITECTURE AND MARINE ENGINEERING,Engineering,1258,16,1123,135,0.107313,758,...,150,692,40,0.050125,70000,43000,80000,529,102,0
4,5,2405,CHEMICAL ENGINEERING,Engineering,32260,289,21239,11021,0.341631,25694,...,5180,16697,1672,0.061098,65000,50000,75000,18314,4440,972

In [51]:
'''We will be answering the following questions using these two datsets:
1) How many students are there in each Major_category in both datasets
2) What % of recent grads have low wage jobs
3) Are there any particular majors in which recent grads fare better than over all population?'''

'We will be answering the following questions using these two datsets:\n1) How many students are there in each Major_category in both datasets\n2) What % of recent grads have low wage jobs\n3) Are there any particular majors in which recent grads fare better than over all population?'

In [6]:
# number of students across all ages in each major_category
ages["Major_category"].value_counts()

Engineering                            29
Education                              16
Humanities & Liberal Arts              15
Biology & Life Science                 14
Business                               13
Health                                 12
Computers & Mathematics                11
Physical Sciences                      10
Agriculture & Natural Resources        10
Psychology & Social Work                9
Social Science                          9
Arts                                    8
Industrial Arts & Consumer Services     7
Law & Public Policy                     5
Communications & Journalism             4
Interdisciplinary                       1
Name: Major_category, dtype: int64

In [9]:
# number of recent grads in each major_category
r_g_maj_cat=r_g["Major_category"].value_counts()

In [ ]:
# Make a dict of the above

In [12]:
r_g_maj_cat_dict=dict(r_g_maj_cat)
r_g_maj_cat_dict

{'Agriculture & Natural Resources': 10,
 'Arts': 8,
 'Biology & Life Science': 14,
 'Business': 13,
 'Communications & Journalism': 4,
 'Computers & Mathematics': 11,
 'Education': 16,
 'Engineering': 29,
 'Health': 12,
 'Humanities & Liberal Arts': 15,
 'Industrial Arts & Consumer Services': 7,
 'Interdisciplinary': 1,
 'Law & Public Policy': 5,
 'Physical Sciences': 10,
 'Psychology & Social Work': 9,
 'Social Science': 9}

In [37]:
total_low_wage=r_g["Low_wage_jobs"].sum()
total_grads=r_g['Total'].sum()

low_wage_prop=((total_low_wage / total_grads)*100)

In [16]:
total_low_wage

667610

In [17]:
total_grads

6776015

In [38]:
low_wage_prop

9.852546076122913

In [39]:
ages.columns

Index([u'Major_code', u'Major', u'Major_category', u'Total', u'Employed',
       u'Employed_full_time_year_round', u'Unemployed', u'Unemployment_rate',
       u'Median', u'P25th', u'P75th'],
      dtype='object')

In [40]:
r_g.columns

Index([u'Rank', u'Major_code', u'Major', u'Major_category', u'Total',
       u'Sample_size', u'Men', u'Women', u'ShareWomen', u'Employed',
       u'Full_time', u'Part_time', u'Full_time_year_round', u'Unemployed',
       u'Unemployment_rate', u'Median', u'P25th', u'P75th', u'College_jobs',
       u'Non_college_jobs', u'Low_wage_jobs'],
      dtype='object')

In [44]:
ages_short=ages.drop(["Employed_full_time_year_round"],axis=1)

In [46]:
r_g_short=r_g[ages_short.columns]

In [47]:
# This data set has only those cols which are common with ages data.

r_g_short

,Major_code,Major,Major_category,Total,Employed,Unemployed,Unemployment_rate,Median,P25th,P75th
0,2419,PETROLEUM ENGINEERING,Engineering,2339,1976,37,0.018381,110000,95000,125000
1,2416,MINING AND MINERAL ENGINEERING,Engineering,756,640,85,0.117241,75000,55000,90000
2,2415,METALLURGICAL ENGINEERING,Engineering,856,648,16,0.024096,73000,50000,105000
3,2417,NAVAL ARCHITECTURE AND MARINE ENGINEERING,Engineering,1258,758,40,0.050125,70000,43000,80000
4,2405,CHEMICAL ENGINEERING,Engineering,32260,25694,1672,0.061098,65000,50000,75000
5,2418,NUCLEAR ENGINEERING,Engineering,2573,1857,400,0.177226,65000,50000,102000
6,6202,ACTUARIAL SCIENCE,Business,3777,2912,308,0.095652,62000,53000,72000
7,5001,ASTRONOMY AND ASTROPHYSICS,Physical Sciences,1792,1526,33,0.021167,62000,31500,109000
8,2414,MECHANICAL ENGINEERING,Engineering,91227,76442,4650,0.057342,60000,48000,70000
9,2408,ELECTRICAL ENGINEERING,Engineering,81527,61928,3895,0.059174,60000,45000,72000
10,2407,COMPUTER ENGINEERING,Engineering,41542,32506,2275,0.065409,60000,45000,75000
11,2401,AEROSPACE ENGINEERING,Engineering,15058,11391,794,0.065162,60000,42000,70000
12,2404,BIOMEDICAL ENGINEERING,Engineering,14955,10047,1019,0.092084,60000,36000,70000
13,5008,MATERIALS SCIENCE,Engineering,4279,3307,78,0.023043,60000,39000,65000
14,2409,ENGINEERING MECHANICS PHYSICS AND SCIENCE,Engineering,4321,3608,23,0.006334,58000,25000,74000
15,2402,BIOLOGICAL ENGINEERING,Engineering,8925,6170,589,0.087143,57100,40000,76000
16,2412,INDUSTRIAL AND MANUFACTURING ENGINEERING,Engineering,18968,15604,699,0.042876,57000,37900,67000
17,2400,GENERAL ENGINEERING,Engineering,61152,44931,2859,0.059824,56000,36000,69000
18,2403,ARCHITECTURAL ENGINEERING,Engineering,2825,2575,170,0.061931,54000,38000,65000
19,3201,COURT REPORTING,Law & Public Policy,1148,930,11,0.011690,54000,50000,54000
20,2102,COMPUTER SCIENCE,Computers & Mathematics,128319,102087,6884,0.063173,53000,39000,70000
21,1104,FOOD SCIENCE,Agriculture & Natural Resources,4361,3149,338,0.096931,53000,32000,70000
22,2502,ELECTRICAL ENGINEERING TECHNOLOGY,Engineering,11565,8587,824,0.087557,52000,35000,60000
23,2413,MATERIALS ENGINEERING AND MATERIALS SCIENCE,Engineering,2993,2449,70,0.027789,52000,35000,62000
24,6212,MANAGEMENT INFORMATION SYSTEMS AND STATISTICS,Business,18713,16413,1015,0.058240,51000,38000,60000
25,2406,CIVIL ENGINEERING,Engineering,53153,43041,3270,0.070610,50000,40000,60000
26,5601,CONSTRUCTION SERVICES,Industrial Arts & Consumer Services,18498,16318,1042,0.060023,50000,36000,60000
27,6204,OPERATIONS LOGISTICS AND E-COMMERCE,Business,11732,10027,504,0.047859,50000,40000,60000
28,2499,MISCELLANEOUS ENGINEERING,Engineering,9133,7428,597,0.074393,50000,39000,65000
29,5402,PUBLIC POLICY,Law & Public Policy,5978,4547,670,0.128426,50000,35000,70000
...,...,...,...,...,...,...,...,...,...,...
143,1105,PLANT SCIENCE AND AGRONOMY,Agriculture & Natural Resources,7416,6594,314,0.045455,32000,22900,40000
144,2308,SCIENCE AND COMPUTER TEACHER EDUCATION,Education,6483,5362,266,0.047264,32000,28000,39000
145,5200,PSYCHOLOGY,Psychology & Social Work,393735,307933,28169,0.083811,31500,24000,41000
146,6002,MUSIC,Arts,60633,47662,3918,0.075960,31000,22300,42000
147,2306,PHYSICAL AND HEALTH EDUCATION TEACHING,Education,28213,23794,1920,0.074667,31000,24000,40000
148,6006,ART HISTORY AND CRITICISM,Humanities & Liberal Arts,21030,17579,1128,0.060298,31000,23000,40000
149,6000,FINE ARTS,Arts,74440,59679,5486,0.084186,30500,21000,41000
150,2901,FAMILY AND CONSUMER SCIENCES,Industrial Arts & Consumer Services,58001,46624,3355,0.067128,30000,22900,40000
151,5404,SOCIAL WORK,Psychology & Social Work,53552,45038,3329,0.068828,30000,25000,35000
152,1103,ANIMAL SCIENCES,Agriculture & Natural Resources,21573,17112,917,0.050862,30000,22000,40000
153,6003,VISUAL AND PERFORMING ARTS,Arts,16250,12870,1465,0.102197,30000,22000,40000
154,2312,TEACHER EDUCATION: MULTIPLE LEVELS,Education,14443,13076,496,0.036546,30000,24000,37000
155,5299,MISCELLANEOUS PSYCHOLOGY,Psychology & Social Work,9628,7653,419,0.051908,30000,20800,40000
156,5403,HUMAN SERVICES AND COMMUNITY ORGANIZATION,Psychology & Social Work,9374,8294,326,0.037819,30000,24000,35000
157,3402,HUMANITIES,Humanities & Liberal Arts,6652,5052,372,0.068584,30000,20000,49000
158,4901,THEOLOGY AND RELIGIOUS VOCATIONS,Humanities & Liberal Arts,30207,24202,1617,0.062628,29000,22000,38000
159,6007,STUDIO ARTS,Arts,16977,13908,1368,0.089552,29000,19200,38300
160,2201,COSMETOLOGY SERVICES AND CULINARY ARTS,Industrial Arts & Consumer Services,10510,8650,510,0.055677,29000,20000,36000
161,1199,MISCELLANEOUS AGRICULTURE,Agriculture & Natural Resources,1488,1290,82,0.059767,29000,23000,42100
162,5502,ANTHROPOLOGY AND ARCHEOLOGY,Humanities & Liberal Arts,38844,29633,3395,0.102792,28000,20000,38000
163,6102,COMMUNICATION DISORDERS SCIENCES AND SERVICES,Health,38279,29763,1487,0.047584,28000,20000,40000
164,2307,EARLY CHILDHOOD EDUCATION,Education,37589,32551,1360,0.040105,28000,21000,35000
165,2603,OTHER FOREIGN LANGUAGES,Humanities & Liberal Arts,11204,7052,846,0.107116,27500,22900,38000
166,6001,DRAMA AND THEATER ARTS,Arts,43249,36165,3040,0.077541,27000,19200,35000
167,3302,COMPOSITION AND RHETORIC,Humanities & Liberal Arts,18953,15053,1340,0.081742,27000,20000,35000
168,3609,ZOOLOGY,Biology & Life Science,8409,6259,304,0.046320,26000,20000,39000
169,5201,EDUCATIONAL PSYCHOLOGY,Psychology & Social Work,2854,2125,148,0.065112,25000,24000,34000
170,5202,CLINICAL PSYCHOLOGY,Psychology & Social Work,2838,2101,368,0.149048,25000,25000,40000
171,5203,COUNSELING PSYCHOLOGY,Psychology & Social Work,4626,3777,214,0.053621,23400,19200,26000
172,3501,LIBRARY SCIENCE,Education,1098,742,87,0.104946,22000,20000,22000

In [48]:
r_g_short['Unemployment_rate'].mean()

0.06858728923255816

In [49]:
ages['Unemployment_rate'].mean()

0.05735545328323702

In [50]:
''' Find the names of majors in which unemployment rate is lower for recent grads than for all ages'''

'let us find the names of majors in which unemployment rate is lower for recent grads than for aall ages'

In [71]:
r_g_maj=r_g["Major"].loc[r_g["Unemployment_rate"] > ages['Unemployment_rate']]

In [72]:
r_g_maj

1                         MINING AND MINERAL ENGINEERING
3              NAVAL ARCHITECTURE AND MARINE ENGINEERING
4                                   CHEMICAL ENGINEERING
5                                    NUCLEAR ENGINEERING
6                                      ACTUARIAL SCIENCE
8                                 MECHANICAL ENGINEERING
9                                 ELECTRICAL ENGINEERING
10                                  COMPUTER ENGINEERING
12                                BIOMEDICAL ENGINEERING
15                                BIOLOGICAL ENGINEERING
18                             ARCHITECTURAL ENGINEERING
20                                      COMPUTER SCIENCE
21                                          FOOD SCIENCE
22                     ELECTRICAL ENGINEERING TECHNOLOGY
24         MANAGEMENT INFORMATION SYSTEMS AND STATISTICS
25                                     CIVIL ENGINEERING
26                                 CONSTRUCTION SERVICES
28                             MISCELLANEOUS ENGINEERING
29                                         PUBLIC POLICY
30                             ENVIRONMENTAL ENGINEERING
31                              ENGINEERING TECHNOLOGIES
32                               MISCELLANEOUS FINE ARTS
33                GEOLOGICAL AND GEOPHYSICAL ENGINEERING
35                                               FINANCE
36                                             ECONOMICS
37                                    BUSINESS ECONOMICS
39     NUCLEAR, INDUSTRIAL RADIOLOGY, AND BIOLOGICAL ...
40                                            ACCOUNTING
41                                           MATHEMATICS
42                      COMPUTER AND INFORMATION SYSTEMS
                             ...
124                                            SOCIOLOGY
125                                           MASS MEDIA
129    LINGUISTICS AND COMPARATIVE LANGUAGE AND LITER...
131                    INTERDISCIPLINARY SOCIAL SCIENCES
134                  GENERAL MEDICAL AND HEALTH SERVICES
135                     PHILOSOPHY AND RELIGIOUS STUDIES
137                      ENGLISH LANGUAGE AND LITERATURE
140                                         LIBERAL ARTS
141                     FILM VIDEO AND PHOTOGRAPHIC ARTS
142                              GENERAL SOCIAL SCIENCES
145                                           PSYCHOLOGY
147               PHYSICAL AND HEALTH EDUCATION TEACHING
148                            ART HISTORY AND CRITICISM
149                                            FINE ARTS
150                         FAMILY AND CONSUMER SCIENCES
151                                          SOCIAL WORK
153                           VISUAL AND PERFORMING ARTS
154                   TEACHER EDUCATION: MULTIPLE LEVELS
155                             MISCELLANEOUS PSYCHOLOGY
157                                           HUMANITIES
158                     THEOLOGY AND RELIGIOUS VOCATIONS
159                                          STUDIO ARTS
161                            MISCELLANEOUS AGRICULTURE
162                          ANTHROPOLOGY AND ARCHEOLOGY
165                              OTHER FOREIGN LANGUAGES
166                               DRAMA AND THEATER ARTS
167                             COMPOSITION AND RHETORIC
169                               EDUCATIONAL PSYCHOLOGY
170                                  CLINICAL PSYCHOLOGY
172                                      LIBRARY SCIENCE
Name: Major, dtype: object

In [76]:
# number of majors where unemploymnet rate was higher for recent grads

len(r_g_maj.unique())

108